import * as yup from "yup";

export const AddCompanySchema = yup.object({
  name: yup.string().required("English Name is required"),
  nameAr: yup.string().required("Arabic Name is required"),
  email: yup.string(),
  status: yup.string().required("Status is required"),
  country: yup.string().required("Country is required"),
  state: yup.string().required("State is required"),
  address: yup.string().required("Address is required"),
  phone: yup.string().required("Phone is required"),
  proCode: yup.array(),
  ownerId: yup.array(),
  licenseNo: yup.string().required("License Number is required"),
  immgCardNo: yup.string().required("Immg Card Number is required"),
  immgCardExpiry: yup.string().required("Immg Card Expire Date is required"),
  licenseIssueDate: yup.string().required("License Issue Date is required"),
  licenseExpiryDate: yup.string().required("License Expire Date is required"),
  establishmentType: yup.string().required("Establishment Type is required"),
  tenancyContractValue: yup.string(),
  tenancyContractExp: yup.date(),
  molCode: yup.string(),
  zipCode: yup.string(),
  licenseIssuePlace: yup.string(),
  molCategory: yup.string(),
  whatsAppNo: yup.string(),
  mobileNo: yup.string(),
  website: yup.string(),
  trn: yup.string(),
  remarks: yup.string(),
});

export const AddCompanyInitailValues = {
  name: "",
  nameAr: "",
  status: "",
  email: "",
  logo: "",
  country: "",
  state: "",
  address: "",
  phone: "",
  proCode: [],
  ownerId: [],
  licenseNo: "",
  immgCardNo: "",
  immgCardExpiry: "",
  licenseIssueDate: "",
  licenseExpiryDate: "",
  establishmentType: "",
  molCode: "",
  molCategory: "",
  whatsAppNo: "",
  mobileNo: "",
  remarks: "",
  trn: "",
  website: "",
};
